import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import path from 'node:path';
import { createIdentity } from '../dist/src/core/peer-transport.js';
import { RelayNode } from '../dist/src/core/relay.js';
import { SeedHostApplication } from '../dist/src/core/application.js';
import { AccountService } from '../dist/src/core/accounts.js';
import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
function vault(){const key=randomBytes(32);return {encrypt(v){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(v),c.final(),c.getAuthTag()]);},decrypt(v){const c=createDecipheriv('aes-256-gcm',key,v.subarray(0,12));c.setAuthTag(v.subarray(-16));return c.update(v.subarray(12,-16),undefined,'utf8')+c.final('utf8');}};}
test('the app signs up once, adds by username, accepts a group, and removes a member without exposing session tokens',async t=>{
 assert.ok(existsSync('dist/src/core/account-integration.js'),'desktop account integration must exist');
 const {AccountIntegration}=await import('../dist/src/core/account-integration.js');
 const root=await mkdtemp(path.join(process.env.TMPDIR,'account-app-'));
 const [di,ri,ai,bi]=await Promise.all(Array.from({length:4},()=>createIdentity()));
 const service=new AccountService(path.join(root,'dir'),di),relay=new RelayNode(path.join(root,'relay'),ri,{log:()=>{}});
 const a=new SeedHostApplication(path.join(root,'a'),ai),b=new SeedHostApplication(path.join(root,'b'),bi);
 t.after(async()=>{await a.close();await b.close();await relay.close();await service.close();await rm(root,{recursive:true,force:true});});
 await service.listen();await relay.open();await relay.listen();await a.open();await b.open();
 await a.joinWithInvite({code:(await relay.createInvite()).code,name:'alice'});await relay.setOwner(ai.fingerprint);
 const ep={...service.endpoint,fingerprint:di.fingerprint},v=vault();
 const alice=new AccountIntegration(path.join(root,'a'),ai,v,a,ep),bob=new AccountIntegration(path.join(root,'b'),bi,v,b,ep);
 await alice.authenticate('register',{username:'alice',password:'fixture-alice-password'});await bob.authenticate('register',{username:'bob',password:'fixture-bob-password'});
 assert.equal('token' in await alice.status(),false);
 const restored=new AccountIntegration(path.join(root,'a'),ai,v,a,ep);assert.equal((await restored.status()).username,'alice');
 const moved=new AccountIntegration(path.join(root,'a'),ai,v,a,{...ep,host:'localhost'});
 assert.equal((await moved.status()).username,'alice','same pinned directory keeps its session when its address changes');
 const wrong=new AccountIntegration(path.join(root,'a'),ai,v,a,{...ep,fingerprint:(await createIdentity()).fingerprint});
 await assert.rejects(wrong.status(),/Saved account/,'moving to a different directory must not disclose the session');
 const { AlwaysOnHost }=await import('../dist/src/core/always-on.js');
 const host=new AlwaysOnHost(path.join(root,'local-host'),await createIdentity(),{host:'127.0.0.1',port:0,gamePorts:[0],discoveryPort:0});
 t.after(()=>host.close());await host.enable('Local group');
 assert.equal(typeof host.ownerInvite,'function','one-click groups must appoint their creator, not an invite redeemer');
 const ownerInvitation=await host.ownerInvite('alice',ai.fingerprint);assert.ok(ownerInvitation.code);
 await assert.rejects(host.ownerInvite('bob',bi.fingerprint),/owner/);
 await restored.send('bob',{fingerprint:relay.identity.fingerprint,serverId:null});const requests=await bob.requests();assert.equal(requests[0].from,'alice');assert.equal('code' in requests[0],false);
 await bob.accept(requests[0].id);assert.equal((await b.listFriends()).members.length,2);
 await a.removeFriend(bi.fingerprint);assert.equal((await a.listFriends()).members.length,1);
 assert.ok(!(await readFile(path.join(root,'a','account.enc'))).includes(Buffer.from('alice')));
});
