import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {chromium} from 'playwright';
let app,page;
before(async()=>{app=await chromium.launch({headless:false});});
after(async()=>{await app?.close();});
async function reset(){await page?.close();page=await app.newPage();page.setDefaultTimeout(6000);await page.addInitScript(()=>{
 const server={id:'alpha',name:'Mossy Hollow',state:'offline',profile:{executable:'java',args:['server.jar']},ownership:{state:'owned',owner:'a'.repeat(64)},mods:{server:[],client:[]}};
 const f=window.fixture={calls:[],groups:[],accountStatus:{configured:false,signedIn:false,online:false},accountRequests:[],state:{deviceId:'a'.repeat(64),server,servers:[{id:server.id,name:server.name,active:true,state:'offline'}],peers:[],settings:{},logs:[],relay:null,onboarding:{version:1,step:'ready',dismissed:true,completed:true,skipped:[],draft:{}},gateway:{enabled:false}}};
 window.dashboardFixture={set:v=>Object.assign(f,v),read:()=>f};
 window.seedhost={call:async(method,payload)=>{f.calls.push({method,payload});if(f.fail===method)throw new Error('TEST failure');if(method==='getState')return structuredClone(f.state);if(method==='listHostingGroups')return f.groups;if(method==='accountStatus')return structuredClone(f.accountStatus);if(method==='accountRequests')return f.accountRequests;if(method==='accountFriends'||method==='accountFriendRequests')return f[method]||[];if(method==='accountDecline'){f.accountRequests=[];return {declined:true,id:payload.id};}if(method==='accountAccept'){Object.assign(f.state,f.acceptState);f.accountRequests=[];return f.acceptResult;}if(method==='accountLogout'){return f.accountStatus={configured:true,signedIn:false,online:false};}if(method==='listSnapshots')return [];if(method==='listFriends')return {members:[],custody:'unknown',holder:null};return undefined;}};
 });await page.goto('file:///'+path.resolve('apps/desktop/index.html').replaceAll('\\','/'));await page.waitForFunction(()=>document.querySelector('#splash').hidden);}

async function signed(){await page.evaluate(()=>{window.dashboardFixture.set({accountStatus:{configured:true,signedIn:true,online:true,username:'alice',detail:'Signed in'},accountRequests:[{id:'invite-1',from:'owner',group:'Shared world',controlEndpoint:{host:'192.168.1.5',port:8443}}]});window.dispatchEvent(new Event('seedhost-account-changed'));});await page.waitForFunction(()=>document.querySelector('#account-heading').textContent==='@alice');}
async function groups(){await page.evaluate(()=>{const call=window.seedhost.call;window.__groups=[{fingerprint:'c'.repeat(64),name:'Waiting world',serverId:null,serverName:null,pending:true,localAuthority:false},{fingerprint:'d'.repeat(64),name:'Created group',serverId:'alpha',serverName:'Mossy Hollow',pending:false,localAuthority:true}];window.seedhost={...window.seedhost,call:async(method,payload)=>method==='listHostingGroups'?window.__groups:call(method,payload)};window.dispatchEvent(new Event('seedhost-account-changed'));});}
test('Friends overview includes pending and bound groups with explicit safe destinations',async()=>{await reset();await signed();await groups();await page.locator('#friends-tab').click();await page.waitForFunction(()=>document.querySelector('#hosting-group-list [data-hosting-group]'));assert.match(await page.locator('#hosting-group-list').textContent(),/Waiting world.*not on this PC/s);assert.match(await page.locator('#hosting-group-list').textContent(),/Created group.*Mossy Hollow/s);await page.locator('[data-hosting-group="'+ 'd'.repeat(64)+'"]').getByRole('button',{name:'Open server Multi-host'}).click();await page.waitForFunction(()=>document.querySelector('#peers-tab').getAttribute('aria-selected')==='true');assert.equal(await page.locator('#server-name').textContent(),'Mossy Hollow');});
test('notification inbox deduplicates polling without marking unread, persists, and isolates signout',async()=>{await reset();await page.evaluate(()=>localStorage.clear());await signed();await page.locator('#notifications-open').click();await page.waitForFunction(()=>document.querySelector('#notifications-list').textContent.includes('@owner'));assert.equal(await page.locator('#notifications-count').textContent(),'1');await page.evaluate(()=>window.dispatchEvent(new Event('seedhost-account-changed')));await page.waitForTimeout(100);assert.equal(await page.locator('#notifications-list [data-notification]').count(),1);await page.locator('#notifications-mark-read').click();assert.equal(await page.locator('#notifications-count').textContent(),'0');await page.locator('#notifications-close').click();await page.reload();await signed();assert.equal(await page.locator('#notifications-count').textContent(),'0');await page.locator('#notifications-open').click();assert.equal(await page.locator('#notifications-list [data-notification]').count(),1);await page.locator('#notifications-close').click();await page.locator('#friends-tab').click();await page.locator('#account-signout').click();await page.locator('#notifications-open').click();assert.equal(await page.locator('#notifications-list [data-notification]').count(),0);assert.doesNotMatch(await page.evaluate(()=>JSON.stringify({...localStorage})),/password|invitationCode|serverDir/);});
for(const pending of [true,false])test(`acceptance confirms exact ${pending?'pending':'bound'} group without requiring auto-park`,async()=>{await reset();await signed();await page.evaluate(pending=>{const pin='c'.repeat(64);const group={fingerprint:pin,name:'Shared world',parkOnStop:false,endpoint:{host:'192.168.1.5',port:8443}};window.fixture.acceptResult={joined:true,group:'Shared world',fingerprint:pin,serverId:pending?null:'alpha',requestId:'invite-1'};window.fixture.acceptState=pending?{pendingGroups:[group],peers:[]}:{relay:group,peers:[{fingerprint:pin,host:'192.168.1.5',port:8443}]};if(!pending){window.fixture.state.server.group=group;window.fixture.state.servers[0].group=group;}},pending);await page.locator('#friends-tab').click();await page.locator('#hosting-request-list [data-account-accept]').click();await page.waitForFunction(()=>document.querySelector('#hosting-request-feedback').textContent.startsWith('Joined Shared world'));assert.doesNotMatch(await page.locator('#hosting-request-feedback').textContent(),/Settings.*group/);});
test('explicit pending download targets the fingerprint and requires bound readback before success',async()=>{await reset();await signed();await groups();await page.locator('#friends-tab').click();await page.waitForFunction(()=>document.querySelector('#hosting-group-list [data-hosting-group]'));await page.locator('[data-hosting-group="'+ 'c'.repeat(64)+'"] button').click();await page.waitForFunction(()=>document.querySelector('#hosting-group-feedback').textContent.includes('not confirmed'));const calls=await page.evaluate(()=>window.fixture.calls);assert.deepEqual(calls.find(c=>c.method==='claimPendingGroup').payload,{fingerprint:'c'.repeat(64)});assert.equal(calls.some(c=>c.method==='startServer'),false);});
test('sign-in refreshes request inbox immediately rather than waiting for a poll',async()=>{await reset();await page.evaluate(()=>{const call=window.seedhost.call;window.seedhost.call=async(m,p)=>{if(m==='accountRegister'){window.fixture.accountStatus={configured:true,signedIn:true,online:true,username:'alice',detail:'Signed in'};window.fixture.accountRequests=[{id:'fresh-request',from:'owner',group:'Shared world',controlEndpoint:{host:'192.168.1.5',port:8443}}];return window.fixture.accountStatus;}return call(m,p);};window.fixture.accountStatus={configured:true,signedIn:false,online:false};window.dispatchEvent(new Event('seedhost-account-changed'));});await page.waitForFunction(()=>document.querySelector('#account-dialog').open);await page.locator('#account-username').fill('alice');await page.locator('#account-password').fill('Fixture-only-not-a-real-password');await page.locator('#account-submit').click();await page.waitForFunction(()=>document.querySelector('#hosting-request-list [data-account-accept="fresh-request"]'),undefined,{timeout:3000});});
test('loopback hosting routes explain that account connectivity does not connect a friend’s PC',async()=>{await reset();await signed();await page.evaluate(()=>{window.fixture.accountRequests[0].id='loopback-invite';window.fixture.accountRequests[0].controlEndpoint.host='127.0.0.1';window.dispatchEvent(new Event('seedhost-account-changed'));});await page.waitForFunction(()=>document.querySelector('#hosting-request-list').textContent.includes('127.0.0.1'));assert.match(await page.locator('#hosting-request-list').textContent(),/same.PC only/i);assert.match(await page.locator('#hosting-request-list').textContent(),/another PC.*cannot|cannot.*another PC/i);assert.match(await page.locator('#notifications-list').textContent(),/same.PC.only|cannot reach/i);});
test('server failure notifications navigate to the server and never infer hosting from custody',async()=>{await reset();await signed();await page.evaluate(()=>{window.seedNotifications.servers(window.fixture.state);window.fixture.state.servers[0].ownerName='This PC';window.seedNotifications.servers(window.fixture.state);window.fixture.fail='startServer';});await page.locator('#server-list [data-action="open"]').click();await page.locator('#start-server').click();await page.waitForFunction(()=>document.querySelector('#error-banner').textContent.includes('TEST failure'));await page.locator('#notifications-open').click();await page.waitForFunction(()=>document.querySelector('#notifications-list').textContent.includes('could not start'));assert.doesNotMatch(await page.locator('#notifications-list').textContent(),/Server started/);await page.locator('#notifications-list button').filter({hasText:'could not start'}).click();await page.waitForFunction(()=>document.querySelector('#operate-tab').getAttribute('aria-selected')==='true');});
test('notification clearing retains deduplication, account rename isolates history, and entries are bounded',async()=>{await reset();await signed();await page.evaluate(()=>{for(let i=0;i<120;i++)window.seedNotifications.requests([{id:'request-'+i,from:'owner'}],[]);});await page.locator('#notifications-open').click();assert.equal(await page.locator('#notifications-list [data-notification]').count(),100);await page.locator('#notifications-clear').click();await page.evaluate(()=>window.dispatchEvent(new Event('seedhost-account-changed')));assert.equal(await page.locator('#notifications-list [data-notification]').count(),0);await page.evaluate(()=>{window.fixture.accountStatus.username='bob';window.fixture.accountRequests=[];window.dispatchEvent(new Event('seedhost-account-changed'));});await page.waitForFunction(()=>document.querySelector('#account-heading').textContent==='@bob');assert.equal(await page.locator('#notifications-count').textContent(),'0');assert.equal(await page.locator('#notifications-list [data-notification]').count(),0);});
test('observed process transitions create one notification per transition across polling',async()=>{await reset();await signed();await page.evaluate(()=>{window.fixture.state.servers[0].state='running';document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>document.querySelector('#notifications-list').textContent.includes('Server started'));await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));assert.equal(await page.locator('#notifications-list button').filter({hasText:'Server started'}).count(),1);await page.evaluate(()=>{window.fixture.state.servers[0].state='offline';document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>document.querySelector('#notifications-list').textContent.includes('Server stopped'));});
test('Multi-host invites capture server and group before directory awaits',async()=>{await reset();await signed();await page.evaluate(()=>{window.fixture.state.relay={fingerprint:'d'.repeat(64),name:'Created group',parkOnStop:false};window.fixture.state.server.group={fingerprint:'d'.repeat(64),parkOnStop:false};window.fixture.accountFriends=[{username:'owner'}];const call=window.seedhost.call;window.seedhost.call=async(m,p)=>m==='accountSend'?(window.fixture.calls.push({method:m,payload:p}),{username:p.username,group:p.fingerprint}):call(m,p);window.dispatchEvent(new Event('seedhost-account-changed'));});await page.locator('#server-list [data-action="open"]').click();await page.locator('#peers-tab').click();await page.waitForFunction(()=>document.querySelector('#hosting-friend-list [data-host-invite]'));await page.locator('#hosting-friend-list [data-host-invite]').click();await page.waitForFunction(()=>document.querySelector('#hosting-friend-feedback').textContent.includes('sent to'));assert.deepEqual((await page.evaluate(()=>window.fixture.calls)).find(c=>c.method==='accountSend').payload,{username:'owner',fingerprint:'d'.repeat(64),serverId:'alpha'});});
test('bound acceptance refuses metadata for a different server even with matching group name and endpoint',async()=>{await reset();await signed();await page.evaluate(()=>{const group={fingerprint:'c'.repeat(64),name:'Shared world',parkOnStop:false,endpoint:{host:'192.168.1.5',port:8443}};window.fixture.acceptState={relay:group};window.fixture.acceptResult={joined:true,group:'Shared world',fingerprint:group.fingerprint,serverId:'another-server',requestId:'invite-1'};});await page.locator('#friends-tab').click();await page.locator('#hosting-request-list [data-account-accept]').click();await page.waitForFunction(()=>document.querySelector('#hosting-request-feedback').textContent.includes('could not be confirmed'));});
test('A→B→A world switches fence late hosting invitation success and clear old feedback',async()=>{await reset();await signed();await page.evaluate(()=>{const f=window.fixture;f.state.relay={fingerprint:'d'.repeat(64),name:'Created group'};f.state.server.group=f.state.relay;f.accountFriends=[{username:'owner'}];const call=window.seedhost.call;window.seedhost.call=async(m,p)=>{if(m==='accountSend'){f.sending=true;await new Promise(resolve=>f.releaseSend=resolve);return {username:p.username,group:p.fingerprint};}return call(m,p);};window.dispatchEvent(new Event('seedhost-account-changed'));});await page.locator('#server-list [data-action="open"]').click();await page.locator('#peers-tab').click();await page.waitForFunction(()=>document.querySelector('#hosting-friend-list [data-host-invite]'));await page.locator('#hosting-friend-list [data-host-invite]').click();await page.waitForFunction(()=>window.fixture.sending);await page.evaluate(()=>{window.fixture.original=window.fixture.state.server;window.fixture.state.server={...window.fixture.original,id:'bravo',name:'Other world'};document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>document.querySelector('#server-name').textContent==='Other world');await page.evaluate(()=>{window.fixture.state.server=window.fixture.original;document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>document.querySelector('#server-name').textContent==='Mossy Hollow');await page.evaluate(()=>window.fixture.releaseSend());await page.waitForFunction(()=>!document.querySelector('#hosting-add-submit').disabled);assert.doesNotMatch(await page.locator('#hosting-friend-feedback').textContent(),/sent to/);});
test('a stale account-status poll cannot restore another account after signout',async()=>{await reset();await signed();await page.evaluate(()=>{const f=window.fixture,call=window.seedhost.call;let held=false;window.seedhost.call=async(m,p)=>{if(m==='accountStatus'&&!held){held=true;f.pollHeld=true;const old=structuredClone(f.accountStatus);await new Promise(resolve=>f.releasePoll=resolve);return old;}return call(m,p);};window.dispatchEvent(new Event('seedhost-account-changed'));});await page.waitForFunction(()=>window.fixture.pollHeld);await page.locator('#friends-tab').click();await page.locator('#account-signout').click();await page.waitForFunction(()=>document.querySelector('#account-signout').hidden);await page.evaluate(()=>window.fixture.releasePoll());await page.waitForTimeout(100);assert.equal(await page.locator('#account-signout').isHidden(),true);assert.equal(await page.locator('#notifications-count').textContent(),'0');});
test('manual Friends refresh redraws hosting groups without waiting for polling',async()=>{await reset();await signed();await page.locator('#friends-tab').click();await page.evaluate(()=>window.fixture.groups=[{fingerprint:'e'.repeat(64),name:'Newly joined group',serverId:null,serverName:null,pending:true,localAuthority:false}]);await page.locator('#hosting-requests-refresh').click();await page.waitForFunction(()=>document.querySelector('#hosting-group-list').textContent.includes('Newly joined group'),undefined,{timeout:3000});});
test('acceptance confirms the exact bound group even when another server remains selected',async()=>{await reset();await signed();await page.evaluate(()=>{const pin='c'.repeat(64);window.fixture.acceptState={relay:null,peers:[{fingerprint:pin,host:'192.168.1.5',port:8443}],servers:[...window.fixture.state.servers,{id:'shared',name:'Shared world',group:{fingerprint:pin,parkOnStop:false}}]};window.fixture.acceptResult={joined:true,group:'Shared world',fingerprint:pin,serverId:'shared',requestId:'invite-1'};});await page.locator('#friends-tab').click();await page.locator('#hosting-request-list [data-account-accept]').click();await page.waitForFunction(()=>document.querySelector('#hosting-request-feedback').textContent.startsWith('Joined Shared world'));assert.equal(await page.evaluate(()=>window.fixture.state.server.id),'alpha');});
test('busy server history cannot evict deduplication of a still-waiting invitation',async()=>{await reset();await signed();await page.evaluate(()=>{const now=Date.now;let tick=now();try{Date.now=()=>++tick;for(let i=0;i<520;i++)window.seedNotifications.failure('startServer','alpha');window.seedNotifications.requests([],window.fixture.accountRequests);}finally{Date.now=now;}});assert.equal(await page.locator('#notifications-list button').filter({hasText:'hosting invitation'}).count(),0);});
test('a late server failure cannot publish into a different signed-in account',async()=>{await reset();await signed();await page.evaluate(()=>{const call=window.seedhost.call;window.seedhost.call=async(m,p)=>{if(m==='startServer'){window.fixture.startHeld=true;await new Promise(resolve=>window.fixture.releaseStart=resolve);throw new Error('TEST delayed start failure');}return call(m,p);};});await page.locator('#server-list [data-action="open"]').click();await page.locator('#start-server').click();await page.waitForFunction(()=>window.fixture.startHeld);await page.evaluate(()=>{window.fixture.accountStatus={configured:true,signedIn:true,online:true,username:'bob',detail:'Signed in'};window.fixture.accountRequests=[];window.dispatchEvent(new Event('seedhost-account-changed'));});await page.waitForFunction(()=>document.querySelector('#account-heading').textContent==='@bob');await page.evaluate(()=>window.fixture.releaseStart());await page.waitForFunction(()=>document.querySelector('#error-banner').textContent.includes('delayed start failure'));assert.equal(await page.locator('#notifications-list button').filter({hasText:'could not start'}).count(),0);});
test('account A→B→A cannot revive an obsolete server failure callback',async()=>{await reset();await signed();await page.evaluate(()=>{const failure=window.seedNotifications.captureFailure();window.seedNotifications.setAccount({signedIn:true,username:'bob'});window.seedNotifications.setAccount({signedIn:true,username:'alice'});failure('startServer','alpha');});assert.equal(await page.locator('#notifications-list button').filter({hasText:'could not start'}).count(),0);});
test('hosting invitations are actionable in global Friends without opening an unrelated server',async()=>{await reset();await signed();await page.locator('#friends-tab').click();assert.equal(await page.locator('#friends-panel #hosting-request-list').count(),1);assert.equal(await page.locator('#peers-panel #hosting-request-list').count(),0);await page.locator('#hosting-request-list [data-account-decline]').click();await page.waitForFunction(()=>document.querySelector('#hosting-request-feedback').textContent==='Invitation declined.');assert.equal((await page.evaluate(()=>window.dashboardFixture.read())).calls.some(c=>c.method==='selectServer'),false);});
test('owner can configure a group-specific existing control route with explicit unverified guidance and readback',async()=>{
 await reset();await signed();await groups();
 await page.evaluate(()=>{const call=window.seedhost.call;const pin='d'.repeat(64);let route={fingerprint:pin,listener:{host:'127.0.0.1',port:47627},advertised:{host:'127.0.0.1',port:47627},reachability:'unverified'};window.seedhost.call=async(m,p)=>{if(m==='getHostingControlRoute')return structuredClone(route);if(m==='setHostingControlRoute'){window.fixture.calls.push({method:m,payload:p});route={...route,advertised:{host:p.host,port:p.port}};return structuredClone(route);}return call(m,p);};});
 await page.locator('#friends-tab').click();await page.locator('[data-hosting-group="'+'d'.repeat(64)+'"] [data-control-route]').click();
 await page.locator('#hosting-route-dialog[open]').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#hosting-route-host').value==='127.0.0.1');
 assert.match(await page.locator('#hosting-route-dialog').textContent(),/does not create.*tunnel|existing.*forward/i);
 await page.locator('#hosting-route-host').fill('group.example');await page.locator('#hosting-route-port').fill('8443');await page.locator('#hosting-route-save').click();
 await page.waitForFunction(()=>document.querySelector('#hosting-route-feedback').textContent.includes('Saved'));
 assert.match(await page.locator('#hosting-route-feedback').textContent(),/unverified.*new invitation|new invitation.*unverified/i);
 assert.deepEqual((await page.evaluate(()=>window.fixture.calls)).find(c=>c.method==='setHostingControlRoute').payload,{fingerprint:'d'.repeat(64),host:'group.example',port:8443});
});

