import test from 'node:test';
import assert from 'node:assert/strict';
import * as invites from '../dist/src/core/invites.js';
import { createHash } from 'node:crypto';
import { validateCall } from '../dist/src/core/ipc-policy.js';
import { readFile, readdir, mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { RelayNode } from '../dist/src/core/relay.js';
import { createIdentity } from '../dist/src/core/peer-transport.js';
import { PeerHostApplication } from '../dist/src/core/application.js';

// Generated by the pre-preview v1 encoder; preserve compatibility with existing pasteable codes.
const existingCode = 'PEERHOST-AQEjRWeJq83vASNFZ4mrze8BI0VniavN7wEjRWeJq83vABEiM0RVZneImaq7zN3u______9j5w4YZnJpZW5kLmV4YW1wbGVGcmllbmRz4oCZIGhvc3RpbmcgZ3JvdXCGE3i3Img';
const expectedPreview = {
  relayName: 'Friends’ hosting group',
  host: 'friend.example',
  port: 25575,
  relayFingerprint: '0123456789abcdef'.repeat(4),
  expiresAt: 0xffffffff * 1000,
};

test('preview projects only public metadata from an existing canonical v1 invitation', () => {
  assert.equal(typeof invites.previewInvite, 'function', 'read-only invitation preview must be exported');
  const decoded = invites.decodeInvite(existingCode);
  assert.equal(invites.encodeInvite(decoded), existingCode, 'the wire format remains unchanged');
  const preview = invites.previewInvite(`  ${existingCode}\n`);
  assert.deepEqual(preview, expectedPreview);
  assert.deepEqual(Object.keys(preview), ['relayName', 'host', 'port', 'relayFingerprint', 'expiresAt']);
  assert.equal(Object.hasOwn(preview, 'token'), false);
  assert.equal(JSON.stringify(preview).includes(decoded.token.toString('hex')), false);
  preview.relayName = 'Changed locally';
  assert.deepEqual(invites.previewInvite(existingCode), expectedPreview, 'preview output does not mutate the invitation');
  assert.equal(invites.encodeInvite(decoded), existingCode);
});

function rewrittenEnvelope(change) {
  const body = Buffer.from(existingCode.slice('PEERHOST-'.length), 'base64url').subarray(0, -6);
  change(body);
  const checksum = createHash('sha256').update(body).digest().subarray(0, 6);
  return 'PEERHOST-' + Buffer.concat([body, checksum]).toString('base64url');
}

test('preview preserves decoder rejection of malformed, unsupported and expired invitations', () => {
  const expired = invites.encodeInvite({ ...invites.decodeInvite(existingCode), expiresAt: 0 });
  const invalidCodes = [undefined, null, 42, {}, '', 'not an invite', 'PEERHOST-',
    existingCode.slice(0, -4), existingCode + '=', existingCode + 'A',
    existingCode.slice(0, -1) + (existingCode.endsWith('A') ? 'B' : 'A'),
    rewrittenEnvelope(body => { body[0] = 2; }),
    rewrittenEnvelope(body => { body[55] += 1; }),
    rewrittenEnvelope(body => { body.writeUInt16BE(0, 53); }),
    rewrittenEnvelope(body => { body.fill(45, 57, 57 + body[55]); }),
    rewrittenEnvelope(body => { body[57 + body[55]] = 0; }),
    rewrittenEnvelope(body => { body[57 + body[55]] = 255; }), expired];
  for (const code of invalidCodes) {
    let decoderError;
    assert.throws(() => invites.decodeInvite(code), error => { decoderError = error.message; return true; });
    assert.throws(() => invites.previewInvite(code), error => error.message === decoderError);
  }
  assert.throws(() => invites.previewInvite(expired), /expired/i);
  assert.deepEqual(invites.previewInvite(existingCode), expectedPreview, 'rejected previews leave valid invitations unchanged');
});

const rendererUrl = 'file:///trusted/peerhost/index.html';
const trusted = { senderId: 9, expectedSenderId: 9, isMainFrame: true };
const call = (method, payload) => validateCall(method, payload, rendererUrl, rendererUrl, trusted);

test('preview IPC accepts only one bounded code from the exact privileged main frame', () => {
  assert.doesNotThrow(() => call('previewInvite', { code: existingCode }), 'preview must be a recognized IPC method');
  for (const code of [existingCode, ` \n${existingCode}\n `, 'a'.repeat(1500)]) {
    assert.deepEqual(call('previewInvite', { code }), { code });
    assert.equal(call('joinWithInvite', { code, name: 'Friend' }).code, code, 'join and preview have the same code bounds');
  }
  for (const code of ['', ' \n\t ', 'a'.repeat(1501), existingCode + '\0', null, 1, {}]) {
    assert.throws(() => call('previewInvite', { code }), /Invalid/i);
    assert.throws(() => call('joinWithInvite', { code, name: 'Friend' }), /Invalid/i);
  }
  for (const payload of [undefined, null, [], existingCode, {}, { code: existingCode, name: 'Friend' },
    { code: existingCode, relayName: 'Forged group' }, { code: existingCode, preview: expectedPreview }]) {
    assert.throws(() => call('previewInvite', payload), /Invalid/i);
  }
  for (const context of [undefined, { ...trusted, senderId: 10 }, { ...trusted, expectedSenderId: 10 },
    { ...trusted, isMainFrame: false }, { ...trusted, isMainFrame: 'true' },
    { ...trusted, senderId: 0, expectedSenderId: 0 }, { ...trusted, senderId: 9.5, expectedSenderId: 9.5 }]) {
    assert.throws(() => validateCall('previewInvite', { code: existingCode }, rendererUrl, rendererUrl, context), /Untrusted IPC sender/);
  }
  for (const url of ['https://attacker.invalid', rendererUrl + '?forged=1', rendererUrl + '#forged', 'file:///trusted/peerhost/other.html']) {
    assert.throws(() => validateCall('previewInvite', { code: existingCode }, url, rendererUrl, trusted), /Untrusted IPC sender/);
  }
});

// Execute the real main IPC callback with real validation/decoding and inert UI/backend seams.
// Importing Electron's entire main entry point would initialize a profile and a real app window.
async function mainHarness({ backend, confirm = async () => { throw new Error('Unexpected consent dialog'); } } = {}) {
  const text = await readFile(new URL('../dist/apps/desktop/main.js', import.meta.url), 'utf8');
  const start = text.indexOf("ipcMain.handle('peerhost:call',");
  const end = text.indexOf('tray = new Tray(', start);
  assert.ok(start >= 0 && end > start, 'the validated native IPC registration exists');
  const registration = text.slice(start, end);
  const mainFrame = { url: rendererUrl };
  const window = { webContents: { id: trusted.senderId, mainFrame } };
  const inertBackend = backend ?? new Proxy({}, { get(_target, key) { throw new Error(`Unexpected backend access: ${String(key)}`); } });
  let handler;
  const ipcMain = { handle(channel, callback) { assert.equal(channel, 'peerhost:call'); handler = callback; } };
  new Function('ipcMain', 'validateCall', 'previewInvite', 'decodeInvite', 'backend', 'confirm', 'window', 'rendererUrl', registration)
    (ipcMain, validateCall, invites.previewInvite, invites.decodeInvite, inertBackend, confirm, window, rendererUrl);
  assert.equal(typeof handler, 'function');
  const event = { sender: { id: trusted.senderId }, senderFrame: mainFrame };
  return {
    event,
    invoke: (method, payload, senderEvent = event) => handler(senderEvent, method, payload),
  };
}

async function filesUnder(root) {
  const files = {};
  for (const entry of await readdir(root, { withFileTypes: true })) {
    const file = path.join(root, entry.name);
    if (entry.isDirectory()) {
      for (const [name, content] of Object.entries(await filesUnder(file))) files[path.join(entry.name, name)] = content;
    } else files[entry.name] = (await readFile(file)).toString('hex');
  }
  return files;
}

test('native preview is local and leaves pending invitations and trust records unchanged', async t => {
  const harness = await mainHarness();
  let preview;
  await assert.doesNotReject(async () => { preview = await harness.invoke('previewInvite', { code: existingCode }); },
    'main must route preview without consent or backend access');
  assert.deepEqual(preview, expectedPreview);

  const root = await mkdtemp(path.join(process.env.TMPDIR || tmpdir(), 'peerhost-invite-preview-'));
  const relay = new RelayNode(root, await createIdentity(), { name: 'Offline friend group', log() {} });
  t.after(async () => { await relay.close(); await rm(root, { recursive: true, force: true }); });
  await relay.open();
  const invitation = await relay.createInvite({ advertise: { host: '127.0.0.1', port: 47625 } });
  assert.equal(Boolean(relay.endpoint), false, 'no listener or remote service is needed to preview');
  const before = await filesUnder(root);
  const expected = { relayName: 'Offline friend group', host: '127.0.0.1', port: 47625,
    relayFingerprint: relay.identity.fingerprint, expiresAt: invitation.expiresAt };
  for (let count = 0; count < 2; count++) {
    assert.deepEqual(await harness.invoke('previewInvite', { code: invitation.code }), expected);
  }
  const expired = invites.encodeInvite({ ...invites.decodeInvite(invitation.code), expiresAt: 0 });
  for (const code of ['bad code', invitation.code.slice(0, -4), expired]) {
    await assert.rejects(harness.invoke('previewInvite', { code }), /invite/i);
  }
  await assert.rejects(harness.invoke('previewInvite', { code: invitation.code, name: 'Extra key' }), /Invalid/);
  for (const event of [
    { ...harness.event, sender: { id: trusted.senderId + 1 } },
    { ...harness.event, senderFrame: { url: rendererUrl } },
    { ...harness.event, senderFrame: undefined },
    { ...harness.event, senderFrame: { url: 'https://attacker.invalid' } },
  ]) await assert.rejects(harness.invoke('previewInvite', { code: invitation.code }, event), /Untrusted IPC sender/);
  assert.deepEqual(await filesUnder(root), before, 'preview never redeems tokens or writes relay state');
  assert.deepEqual(relay.trusted, []);
});

test('native joining rejects malformed or expired codes before prompting or enrollment', async () => {
  const dialogs = [];
  const harness = await mainHarness({ confirm: async (...args) => { dialogs.push(args); return false; } });
  const expired = invites.encodeInvite({ ...invites.decodeInvite(existingCode), expiresAt: 0 });
  for (const code of ['not an invitation', existingCode.slice(0, -4), expired]) {
    await assert.rejects(harness.invoke('joinWithInvite', { code, name: 'Joining friend' }), /invite/i,
      'the exact join code must be independently decoded before the native dialog');
  }
  assert.deepEqual(dialogs, [], 'invalid invitations never request consent');
  await assert.rejects(harness.invoke('joinWithInvite', { code: existingCode, name: 'Joining friend', preview: expectedPreview }), /Invalid/);
  assert.deepEqual(dialogs, [], 'renderer-supplied metadata is never accepted');
});

test('native join consent describes the exact current code and its hosting permissions', async () => {
  const dialogs = [];
  const harness = await mainHarness({ confirm: async (...args) => { dialogs.push(args); return false; } });
  await harness.invoke('previewInvite', { code: existingCode });
  const currentInvite = { ...invites.decodeInvite(existingCode), relayName: 'The actual joining group', host: '127.0.0.1',
    port: 47626, relayFingerprint: 'b'.repeat(64), expiresAt: 0xffffffff - 10 };
  const currentCode = invites.encodeInvite(currentInvite);
  assert.equal(await harness.invoke('joinWithInvite', { code: currentCode, name: 'Joining friend' }), undefined);
  assert.equal(dialogs.length, 1, 'canceling join shows one dialog and performs no backend action');
  const [message, detail] = dialogs[0];
  const shown = `${message}\n${detail}`;
  assert.ok(shown.includes(currentInvite.relayName), 'consent must display the decoded group name, not an earlier preview');
  assert.ok(shown.includes(`${currentInvite.host}:${currentInvite.port}`), 'consent must display the decoded host and port');
  assert.ok(shown.includes(new Date(currentInvite.expiresAt * 1000).toISOString()), 'consent must display an unambiguous expiry');
  assert.ok(shown.includes(currentInvite.relayFingerprint), 'consent must display the full relay fingerprint');
  assert.match(shown, /compare[\s\S]*friend[\s\S]*trusted channel/i);
  assert.match(shown, /group[\s\S]*read[\s\S]*world files[\s\S]*share hosting/i);
  assert.match(shown, /does not download or start a server/i);
  assert.match(shown, /clean stops will attempt to send the world to the always-on PC/i);
  assert.match(shown, /offline[\s\S]*world stays local/i);
  assert.match(shown, /parsed locally/i);
  assert.match(shown, /do not prove[\s\S]*authentic[\s\S]*reachable/i);
  assert.equal(shown.includes(expectedPreview.relayName), false);
  assert.equal(shown.includes(currentInvite.token.toString('hex')), false);
  assert.equal(shown.includes(currentCode), false, 'consent never leaks the bearer token via the invite code');
});

test('native approval forwards the original validated join payload only after consent', async () => {
  const payload = { code: ` \n${existingCode}\n`, name: 'Joining friend' };
  const calls = [];
  let approved = false;
  const backend = { async joinWithInvite(input) {
    assert.equal(approved, true, 'enrollment is never attempted before approval');
    calls.push(input);
    return { relayName: expectedPreview.relayName };
  } };
  const harness = await mainHarness({ backend, confirm: async () => {
    assert.deepEqual(calls, []);
    approved = true;
    return true;
  } });
  assert.deepEqual(await harness.invoke('joinWithInvite', payload), { relayName: expectedPreview.relayName });
  assert.deepEqual(calls, [payload], 'the backend retains its own validation of the original code and friend name');
});

test('backend final validation still rejects an invitation that expires during native consent', async t => {
  const root = await mkdtemp(path.join(process.env.TMPDIR || tmpdir(), 'peerhost-invite-consent-'));
  const application = new PeerHostApplication(root, await createIdentity());
  t.after(async () => { await application.close(); await rm(root, { recursive: true, force: true }); });
  await application.open();
  const before = await filesUnder(root);
  const invite = { ...invites.decodeInvite(existingCode), expiresAt: Math.floor(Date.now() / 1000) + 3600 };
  const code = invites.encodeInvite(invite);
  t.mock.timers.enable({ apis: ['Date'], now: Date.now() });
  let dialogs = 0;
  const harness = await mainHarness({ backend: application, confirm: async () => {
    dialogs++;
    t.mock.timers.setTime((invite.expiresAt + 1) * 1000);
    return true;
  } });
  await assert.rejects(harness.invoke('joinWithInvite', { code, name: 'Joining friend' }), /expired/i);
  assert.equal(dialogs, 1);
  assert.deepEqual(await filesUnder(root), before, 'expired-after-consent join writes no application state');
  const state = await application.getState();
  assert.equal(state.relay, null);
  assert.deepEqual(state.peers, []);
});
